name: Create Release Pull Request

on:
  workflow_dispatch:
    inputs:
      nextVersion:
        description: 'Next Version (vX.Y.Z)'
        required: true
jobs:
  create-release-pull-request:
    name: Create Release Pull Request
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
          fetch-depth: 0
    - name: install ghch
      id: setup-ghch
      run: |
        TEMPDIR=$(mktemp -d)
        curl -fsSL https://github.com/Songmu/ghch/releases/download/${GHCH_VERSION}/ghch_${GHCH_VERSION}_linux_amd64.tar.gz | tar -xz --strip-components 1 -C $TEMPDIR
        echo "::set-output name=ghch-path::$TEMPDIR/ghch"
      env:
        GHCH_VERSION: v0.10.2
        TZ: Asia/Tokyo
    - name: Generate New Changelog
      run: |
        ${{ steps.setup-ghch.outputs.ghch-path }} -w --next-version=${{ github.event.inputs.nextVersion }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        # token: ${{ secrets.PERSONAL_ACCESS_TOKEN }} # TODO: Without this configuration, this p-r does not trigger another workflow (= CI)
        branch: release-${{ github.event.inputs.nextVersion}}
        commit-message: Prepare for release ${{ github.event.inputs.nextVersion}}
        title: Release ${{ github.event.inputs.nextVersion}}
        body: |
          ## How to release this version
          1. Review and modify CHANGELOG.md
          2. Merge this pull request
          3. Wait a while, and check https://github.com/${{ github.repository}}/releases/tag/${{ github.event.inputs.nextVersion }}
